### ISSUE TITLE
Unable to install version 1.4 from Nuget

### ISSUE THREAD

**Issue by ganeshan** [JasperFx/baseline#11]
![image](https://user-images.githubusercontent.com/115037/28341136-55797fae-6be0-11e7-8b6a-dd2af073d259.png)
I tried installing Marten from NuGet, the install did not succeed due to its dependency on baseline. When I tried installing baseline the error message, as shown above, was observed.

**Comment by jeremydmiller** [comment]
@ganeshan You're going to have to provide a *lot* more information than that. What .Net version are you targeting, what Nuget client, etc. Otherwise this isn't going to be actionable in any way

**Comment by ganeshan** [comment]
@jeremydmiller ,I created a console app in Visual Studio, set the Target Framework to 

> Attempting to gather dependency information for package 'Baseline.1.4.0' with respect to project 'Baseline', targeting '.NETFramework,Version=v4.5.2'
Gathering dependency information took 350.99 ms
Attempting to resolve dependencies for package 'Baseline.1.4.0' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Baseline.1.4.0'
Resolved actions to install package 'Baseline.1.4.0'
Retrieving package 'Baseline 1.4.0' from 'Public Feed'.
Retrieving package 'System.Reflection.Extensions 4.3.0' from 'Public Feed'.
Adding package 'System.Reflection.Extensions.4.3.0' to folder 'D:\apps\baseline\packages'
Added package 'System.Reflection.Extensions.4.3.0' to folder 'D:\apps\baseline\packages'
Added package 'System.Reflection.Extensions.4.3.0' to 'packages.config'
Successfully installed 'System.Reflection.Extensions 4.3.0' to Baseline
Adding package 'Baseline.1.4.0' to folder 'D:\apps\baseline\packages'
Added package 'Baseline.1.4.0' to folder 'D:\apps\baseline\packages'
Added package 'Baseline.1.4.0' to 'packages.config'
Successfully installed 'Baseline 1.4.0' to Baseline
Executing nuget actions took 824.69 ms
That worked

**Comment by jeremydmiller** [comment]
So is there a real issue here? I wouldn't have any clue about what Linqpad is doing with Nuget.

**Comment by jeremydmiller** [comment]
I *think* we're past the nuget woes
