### ISSUE TITLE
Delist Bad NuGet Package Versions of Baseline

### ISSUE THREAD

**Issue by bchavez** [JasperFx/baseline#14]
![31702709-9f0898b8-b38d-11e7-81d7-4521ff1060ac](https://user-images.githubusercontent.com/478118/31735540-13a4b45e-b3f7-11e7-83e5-71feae1dd45b.png)

Hey, I finally heard back from the people in the NuGet Ivory tower :tokyo_tower:. They say the solution to resolving this annoying NuGet issue with `Baseline` is to delist the `Baseline` packages that contain the error. The crux of the issue is an empty `id` string in the "dependencies" part of the NuGet `.nuspec` as shown below:

```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<package xmlns="http://schemas.microsoft.com/packaging/2011/10/nuspec.xsd">
  <metadata>
    <id>Baseline</id>
    <version>0.5.0.3</version>
    <title>Baseline</title>
    <authors>Jeremy D. Miller, Brandon Behrens, Andrew Kharlamov</authors>
    <owners>Jeremy D. Miller, Chad Myers, Joshua Arnold, Joshua Flanagan</owners>
    <licenseUrl>https://github.com/JasperFX/Baseline/blob/master/LICENSE.txt</licenseUrl>
    <projectUrl>https://github.com/JasperFX/Baseline</projectUrl>
    <description>Grab bag of generic utilities and extension methods for .Net development</description>
    <dependencies>
      <dependency id="" version="" />
    </dependencies>
  </metadata>
</package>
```

Anyway, I've tried very hard to convince the NuGet team that they need to fix this issue because it really turns out to be their problem but they just now closed my issue: https://github.com/NuGet/NuGetGallery/issues/4494. Their response is to ask the package author to delist the specific NuGet package versions that are affected by the "empty id string" dependency.

So, let's try it and maybe we can finally put this damn issue to rest. If it fails, I'll be back in their front yard.

The following `Baseline` versions that need to be delisted are:
```
0.5.0.3
0.5.0.4
0.5.0.6
0.5.0.7
```
Thanks,
Brian

/cc @jeremydmiller @CoreyKaylor 

For reference, the past issues that others have encountred this issue are: [here](https://github.com/JasperFx/baseline/issues/11), [here](https://github.com/JasperFx/marten/issues/522), and [here](https://github.com/JasperFx/marten/issues/458).

**Comment by jeremydmiller** [comment]
Meh, thanks for tracking that down with them. I de-listed all the Baseline versions < 1.0 before we switched to using `dotnet pack` and a different set of problems

**Comment by bchavez** [comment]
Thanks so much @jeremydmiller for your help. Maybe I need to wait for some cache or index to get updated because it doesn't seem to have worked yet. *sigh* :disappointed: 

Are you okay with the NuGet team nuking the NuGet `Baseline` packages with versions < 1.0 if it comes down to it?

Going to report back to https://github.com/NuGet/NuGetGallery/issues/4494 in a few hours.

**Comment by bchavez** [comment]
The `Baseline` NuGet issue has been finally put to rest. 

https://github.com/NuGet/NuGetGallery/issues/4494#issuecomment-339439985


![screen_740](https://user-images.githubusercontent.com/478118/32019183-367c52f4-b981-11e7-97fd-310b56f981aa.gif)

![giphy](https://user-images.githubusercontent.com/478118/32019322-b013683c-b981-11e7-97dc-a5768680b977.gif)
